export const GET_USERS = "GET_USERS";
export const GET_USERS_ERROR = "USERS_ERROR";

export const USER_LOGIN = "USER_LOGIN";
export const USER_SIGNUP = "USER_SIGNUP";
export const CHECK_EMAIL = "CHECK_EMAIL";
export const CHECK_USERNAME = "CHECK_USERNAME";
export const GET_POLLS = "GET_POLLS";
export const USER_VOTE = "USER_VOTE";
export const CLEAR_PREV_VOTE_RESULT = "CLEAR_PREV_VOTE_RESULT";
export const CLEAR_LOGING_STORE = "CLEAR_LOGING_STORE";

export const USER_LOGIN_ERROR = "USER_LOGIN_ERROR";
export const USER_SIGNUP_ERROR = "USER_SIGNUP_ERROR";
export const CHECK_EMAIL_ERROR = "CHECK_EMAIL_ERROR";
export const CHECK_USERNAME_ERROR = "CHECK_USERNAME_ERROR";
export const GET_POLLS_ERROR = "GET_POLLS_ERROR";
export const USER_VOTE_ERROR = "USER_VOTE_ERROR";
